spring:
    datasource:
        url: jdbc:h2:mem:testdb;DB_CLOSE_ON_EXIT=FALSE
        dbname: testdb
        username: sa
        password: sa
    jpa:
        hibernate:
            ddl-auto: create
        properties:
            hibernate:
                dialect: org.hibernate.dialect.H2Dialect
                forma_sql: true
        show-sql: true
    port: 8080
    h2:
        console:
            enabled: true
    logging:
        level:
            root: TRACE
    kafka:
        bootstrap-servers: localhost:9092
        consumer:
            group-id: myGroup